# model_inference/__init__.py

from model_inference.model_module import ModelConfig
from model_inference.model_module import type_one_model_inference
from model_inference.model_module import type_two_model_inference