name: ai-cfia repository standard

on: 
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
